name: Deploy to S3

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Render final index.html
        run: |
          # Use envsubst to replace placeholders in the template
          envsubst < .site/index.tempate.html > ./site/index.html
        env: 
          SERVER_IP: ${{ vars.SERVER_IP}}
          SERVER_PORT: ${{vars.SERVER_PORT}}

      - name: Sync to S3
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --delete # remove all previous content from the bucket
        env:
          AWS_S3_BUCKET: ${{ vars.DEV_SITE_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
          SOURCE_DIR: ./site  # Deploy index.html from the 'site' folder